config/routes.rb
Travel::Application.routes.draw do
  
  get "author_info/about_edit"
  put "author_info/about_update"

  devise_for :author_infos, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "devise_registrations_callbacks"}

  get "login" => "sessions#new"
  get "logout" => "sessions#del"
  match "sessions" => "sessions#create", :via => :post

  get "venues/pick"
  get "venues/get_venue_info"
  get "venues/get_venue_photos"
  get "venues/get_venue_details"

  get "locations/pick"

  
  %w[about privacy tos why].each do |page|
    get page, :controller => "info", :action => page
  end
  
  resources :author_info do
    member do
      get 'author_page'
    end
  end  
  resources :trip_activities
  resources :trips do
    member do
      get 'showpartial'
      get 'daymapinfo'
      get 'publish_edit'
      get 'publish_confirm'
      get 'publish_add_day'
      get 'publish_delete_day'
      get 'publish_trip_partial_format'
      get 'publish_up_vote'
      put 'publish_update'
      put 'update_individual'
      put 'publish_confirm_update'
      post 'publish_chalo_feedback'
    end
    collection do
      get 'trips_admin'
      get 'publish_new'
      post 'publish_create'
      post 'edit_individual'
    end
    resources :trip_activities do
      member do
        get 'mapinfo'
        get 'carddeck'
        get 'showpartial'
        get 'show_activity_photos'
        get 'publish_trip_activity_edit'
        put 'publish_trip_activity_update'
        post 'add_new_photo'
        delete 'publish_trip_activity_destroy'
      end
      collection do
        get 'move'
        get 'publish_trip_activity_new'
        post 'publish_trip_activity_create'
      end
    end
  end # I nested trip_activities into trips so that we can have routes with /trip/:trip_id/trip_activities/:id hkl
  

  root :to => 'trips#index', :featured => '1'
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end
  
  constraints resque_constraint do
    mount Resque::Server, :at => "/resque"
  end

  
  match "/:username" => "author_info#author_page", via: "get"
  
  unless Rails.application.config.consider_all_requests_local
     match '*not_found', :to => 'errors#error_404'
  end
end

app/controllers/trip_activities_controller.rb
class TripActivitiesController < ApplicationController
  include ApplicationHelper
  include TripActivitiesHelper
  before_filter :load_trip
  before_filter :authorize, :only => [:new, :edit, :create, :update, :destroy, :show_activity_photos, :add_new_photo]
  
  # GET /trip_activities
  # GET /trip_activities.json
  def index
    @trip_activities = @trip.trip_activities.all(:order => "activity_day asc, activity_sequence_number asc")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trip_activities }
    end
  end

  # GET /trip_activities/1
  # GET /trip_activities/1.json
  def show
    begin
      @trip_activity = @trip.trip_activities.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Trip activity not found"
      redirect_to :controller => 'trips', :action => 'index'
      return
    end
    
    respond_to do |format| require 'trip_activities_controller'
      format.html # show.html.erb
      format.json { render json: @trip_activity }
    end
  end
  
  # GET /trip_activities/new
  # GET /trip_activities/new.json
  def new
    @activity = nil
    @trip_activity = @trip.trip_activities.new
    @trip_activity.trip_id = params[:trip_id]
    @latlong = find_location_latlong @trip
    @trip_activities = @trip.trip_activities.all.sort_by {|e| e[:activity_sequence_number]}

    #if we have less than one activity, set the activity_sequence_number to 1
    if @trip_activities.size < 1
      @trip_activity.activity_sequence_number = 1
    else
      #if we have more than one activity, get last activity sequence
      #and set this new activity's position (in the form field), to n+1
      @trip_activity.activity_sequence_number = @trip_activities.last.activity_sequence_number+1
    end
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip_activity }
    end
  end

  # GET /trip_activities/1/edit
  def edit
    begin
      @trip_activity = @trip.trip_activities.find(params[:id])
      @latlong = find_location_latlong @trip
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Trip activity not found"
      redirect_to :controller => 'trips', :action => 'index'
      return
    end
  end

  def report_error format, object
    logger.info "error"
    format.html { render action: "new" }
    format.json { render json: object.errors, status: :unprocessable_entity }
  end
  
  # POST /trip_activities
  # POST /trip_activities.json
  def create
    @trip_activity = nil
    @activity = nil
    @activity_detail = nil
    respond_to do |format|
      if (params[:trip_activity][:activity_type] == "FoodActivity" or params[:trip_activity][:activity_type] == "LocationActivity" or params[:trip_activity][:activity_type] == "TransportActivity")
        if params[:trip_activity][:activity_type] == "FoodActivity"
          logger.info "food activity..."  
          @activity = FoodActivity.new(params[:food_activity])
          @activity.image_urls = params[:selected_images]
          @activity_detail = @activity.restaurant_detail
          if (@activity_detail.nil? or @activity_detail == 0)
            @activity_detail = create_food_venue(@activity[:restaurant_detail_id], @trip.location_id)
            @activity.restaurant_detail = @activity_detail
          end
        elsif params[:trip_activity][:activity_type] == "TransportActivity"
          logger.info "transport acitivity"
          @activity_detail = ""
          @activity = TransportActivity.new(params[:transport_activity])
        elsif params[:trip_activity][:activity_type] == "LocationActivity"
          logger.info "location acitivity"
          @activity = LocationActivity.new(params[:location_activity])
          @activity.image_urls = params[:selected_images]
          @activity_detail = @activity.location_detail
          if (@activity_detail.nil? or @activity_detail == 0)
            @activity_detail = create_location_venue(@activity[:location_detail_id], @trip.location_id)
            @activity.location_detail = @activity_detail
          end
        end   
        
        
        if @activity_detail == nil or @activity_detail.errors.any?
          if @activity_detail.nil?
          else
            logger.info "activity detail errors #{@activity_detail.inspect.errors} "
          end
          format.html { redirect_to new_trip_trip_activity_path(@trip), notice: 'Error during activity creation, retry.'  }
          format.json { render json: @activity_detail.errors, status: :unprocessable_entity }    
        else
          if !(@activity and @activity.save)
            logger.info "\n activity errors #{@activity.errors.messages} "
            format.html { redirect_to new_trip_trip_activity_path(@trip), notice: @activity.errors.full_messages.to_sentence }
            format.json { render json: @activity.errors, status: :unprocessable_entity }    
          else        
            @trip_activity = @trip.trip_activities.create(:activity => @activity, \
            :activity_day => params[:trip_activity][:activity_day], \
            :activity_sequence_number => params[:trip_activity][:activity_sequence_number], \
            :activity_time_type => params[:trip_activity][:activity_time_type])
            if params[:self_trip_activity_photos] != nil
             @photo = @trip_activity.self_trip_activity_photos.new(params[:self_trip_activity_photos])
             if @photo.save
               format.html { redirect_to new_trip_trip_activity_path(@trip), notice: 'Trip activity was successfully created.' }
               format.json { render json: @trip_activity, status: :created, location: @trip_activity }
             else
               @activity.destroy # clean up
               @latlong = find_location_latlong @trip
               format.html { render action: "new", notice: @photo.errors.full_messages.to_sentence  }
               format.json { render json: @trip_activity.errors, status: :unprocessable_entity }
             end
            else
              if @trip_activity.save
                format.html { redirect_to new_trip_trip_activity_path(@trip), notice: 'Trip activity was successfully created.' }
                format.json { render json: @trip_activity, status: :created, location: @trip_activity }
              else
                @activity.destroy # clean up
                @latlong = find_location_latlong @trip
                format.html { render action: "new", notice: @trip_activity.errors.full_messages.to_sentence  }
                format.json { render json: @trip_activity.errors, status: :unprocessable_entity }
              end
            end
          end
        end
      else
        logger.info "invalid value activity type "
        format.html { redirect_to new_trip_trip_activity_path(@trip), notice: 'invalid activity selected' }
        format.json { render json: @trip_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trip_activities/1
  # PUT /trip_activities/1.json
  def update
    begin
      @trip_activity = @trip.trip_activities.find(params[:id])
      @activity = @trip_activity.activity
      @trip_activities = @trip.trip_activities.all.sort_by {|e| e[:activity_sequence_number]}
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Trip activity not found"
      redirect_to :controller => 'trips', :action => 'index'
      return
    end
    
    respond_to do |format|
      if params[:trip_activity][:activity_type] == "FoodActivity"
        @activity.image_urls = (params[:selected_images] != "") ? params[:selected_images] : @activity.image_urls
        values = params[:food_activity]
      elsif params[:trip_activity][:activity_type] == "TransportActivity"
        values = params[:transport_activity]
      elsif params[:trip_activity][:activity_type] == "LocationActivity"
        @activity.image_urls = (params[:selected_images] != "") ? params[:selected_images] : @activity.image_urls
        values = params[:location_activity]
      end        
      if (@activity.update_attributes(values) == false)
        format.html { render action: "edit", notice: @activity.errors.full_messages.to_sentence }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      else
        if @trip_activity.update_attributes(params[:trip_activity])
          format.html { redirect_to trip_trip_activities_path(@trip), notice: 'Trip activity was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit", notice: @trip_activity.errors.full_messages.to_sentence}
          format.json { render json: @trip_activity.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /trip_activities/1
  # DELETE /trip_activities/1.json
  def destroy
    begin
      @trip_activity = @trip.trip_activities.find(params[:id])
      # this is not tested and a very crude way to delete the trip
      @trip_activity.activity.destroy
      @trip_activity.destroy
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Trip activity not found"
      redirect_to :controller => 'trips', :action => 'index'
      return
    end
    respond_to do |format|
      format.html { redirect_to @trip }
      format.json { head :no_content }
    end
  end

  def showpartial
    #logger.info "active #{params.inspect}"
    # @trip_activity = @trip.trip_activities(params[:id])
    begin
      @trip_activity = TripActivity.find(params[:activityid])
      @partial_layout = params[:layout]
      @activity_count = find_sequence_count(@trip_activity.activity_id, @trip_activity.activity_day, @trip_activity.trip_id)
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "Trip activity not found"
      redirect_to :controller => 'trips', :action => 'index'
      return
    end
       

app/helpers/trip_activities_helper.rb
module TripActivitiesHelper

  # this checks to see if a detail (i.e. open hours) is avaialble, if not then just post a empty string rather than nothing at all
  def check_empty_detail(attribute)
    attribute.blank? ? "--" : attribute
  end
  
  # This function gets the image that we want to show on an activity card
  # index details which image to pick if multiple images
  def select_activity_img(activity_id, image_urls, width, index = 0)
    if activity_id != -1
      if activity_id.activity.image_urls.nil? or activity_id.activity.image_urls == ""
        case 
            when activity_id.activity_type == "FoodActivity" then image_urls = activity_id.activity.restaurant_detail[:image_urls]
            when activity_id.activity_type == "LocationActivity" then image_urls = activity_id.activity.location_detail[:image_urls]
            else image_urls = ""
        end
      else
        image_urls = activity_id.activity.image_urls # select image from the activity if chosen by the author
      end
    end
    
    
    image = select_image_given_image_urls(image_urls, width, index)
      #z is in the format of
        #[["https://is1.4sqi.net/pix/77727_kohZm1hN4NDZ6kQVznu7SGUkWk7NeJz6W9Xwa_heiqk.jpg", "612X612", "https://is0.4sqi.net/derived_pix/77727_kohZm1hN4NDZ6kQVznu7SGUkWk7NeJz6W9Xwa_heiqk_300x300.jpg", "300X300", "https://is0.4sqi.net/derived_pix/77727_kohZm1hN4NDZ6kQVznu7SGUkWk7NeJz6W9Xwa_heiqk_100x100.jpg", "100X100", "https://is0.4sqi.net/derived_pix/77727_kohZm1hN4NDZ6kQVznu7SGUkWk7NeJz6W9Xwa_heiqk_36x36.jpg", "36X36"],...]
        #z[picture][size]. odd index numbers are the dimensions and even are urls to the right size in descending size order
  end

  # This function gets the appropriate thumbnail for the filmstrip
  def show_thumbnail(i, width)
    if @sorted_activities[i][:activityid]
      activity_id = @sorted_activities[i][:activityid]
      image_url = select_activity_img(-1, @sorted_activities[i][:image_url], width) 
    else
      "/assets/no-img-holder.png"
    end
  end

  # This function gets the name of the activity venue for the thumbnail captions
  def thumbnail_name(i)
    if @sorted_activities[i][:activityid]
      thumb_name = @sorted_activities[i][:activity_venue_name]
      thumb_name
    else
      ""
    end
  end

  def alt_name_card_image(activity_id)
    this_activity = TripActivity.find(activity_id)
    activity_type = this_activity.activity_type
    case 
        when activity_type == "FoodActivity" then alt_name = this_activity.activity.restaurant_detail[:name]
        when activity_type == "TransportActivity" then alt_name = this_activity.activity.location_detail[:name]
        # when activity_id.activity_type == "LocationActivity" then alt_name = activity_id.activity.transport_detail[:name]
    end
    alt_name
  end
  
  def find_sequence_count(activity_id, activity_day, trip_id)
    activities_same_day = TripActivity.find(:all, :conditions => {:trip_id => trip_id, :activity_day => activity_day}, :order => "activity_sequence_number")
    
    sequence = 1
    activities_same_day.each { |trip_activity|
       if trip_activity.activity_id == activity_id
         break
       end
       sequence = sequence + 1
     }
     sequence = sequence.ordinalize
     sequence
  end
  
  def time_type_to_name(time_type_id)
    name = ""
    case time_type_id
      when "1", "2"
        name = "Morning"
      when "3", "4"
        name =  "Afternoon"
      when "5", "6", "7"
        name =  "Evening"
    end
    name
  end
end

app/views/trip_activities/partials/_activity-card.html.erb
<!-- Begin Activity Container -->
<div class = "activitycontainer">
  <!-- Begin centerimage Container -->
  <div class="centerimage">

      <div class = "progession_group">
        <div class = "activity_card_day_box">Day <%= @trip_activity.activity_day %></div>    
        <div class = "activity_card_count_box"><%= "#{@activity_count}" %></div>
    
        <% if self.is_cant_miss(check_empty_detail(which_detail_type(@trip_activity,"rating")), @trip_activity.cant_miss) %>
          <div class = "activity_card_star_box">
            <%= image_tag('/assets/star.png', {:class => "image_thumbnail"}) %>
          </div>
        <% end %>
      </div>

      <!-- Begin rightcaption -->
      <div class="rightcaption">
        <div id="activity_title">
          <span class="activity_title title"><%= (which_detail_type(@trip_activity,"name")) %></span></br>
          <span class="activity_subtitle caption_large">
            <%= time_type_to_name(@trip_activity.activity_time_type)%>      
              <% if @trip_activity.activity.activity_duration_type %>
                <% if !@trip_activity.activity.activity_duration_type[:activity_duration_name].blank? %>
                <%= "( #{@trip_activity.activity.activity_duration_type[:activity_duration_name]} )" %> 
                <% end %>
              <% else %>
                <%= "( #{@trip_activity.activity[:duration]} )" %>
              <% end %>          
          </span>
        </div>

        <!-- Begin rc_tabs_con -->
        <div class = "rc_tab_con">

          <!-- Begin Tabs -->
          <ul class="nav nav-tabs" id="rc_activity_tabs">
            <li class ="active">
              <a class="rc_activity_tabs_link" href="<%= "#rc_activity_tabs_1_#{@trip_activity.id}" %>" data-toggle="tab">Summary</a>
            </li>
            <li>
              <a class="rc_activity_tabs_link" href="<%= "#rc_activity_tabs_2_#{@trip_activity.id}" %>"data-toggle="tab">Info</a>
            </li>
            <li>
              <a class="rc_activity_tabs_link" href="<%= "#rc_activity_tabs_3_#{@trip_activity.id}" %>" data-toggle="tab">Reviews</a>
            </li>
          </ul>
          <!-- End Tabs -->
          
          <!-- Begin Tab Content -->
          <div class="tab-content">
            <!-- Begin Tab Pane 1 -->
            <div class="rc_activity_tabs_pane tab-pane active" id="<%= "rc_activity_tabs_1_#{@trip_activity.id}" %>">

              <p class="caption_large" id="user_description">
                <%= auto_link(@trip_activity.activity[:description], :html => { :target => '_blank' }) %>
              </p>
              
              <% unless @trip_activity.activity[:quick_tip].blank? %>
                <div class="well well-small caption_quick_tip caption_medium">
                  Quick Tip: <%= auto_link(@trip_activity.activity[:quick_tip], :html => { :target => '_blank' }) %> 
                </div>
              <% end %>

            </div>
            <!-- End Tab Pane 1 -->
            
            <!-- Begin Tab Pane 2 -->
            <div class="rc_activity_tabs_pane tab-pane" id="<%= "rc_activity_tabs_2_#{@trip_activity.id}" %>">
              <div class = "more_info_dl" id="more_info_id">
                <div id = "more-info-buffer-header"></div>
                <div id = "more-info-buffer-content">
                  <dl class = "caption_medium">
                  <dt>Address:</dt>
                  <dd>
                    <address>
                      <%= check_empty_detail(which_detail_type(@trip_activity,"address1")) %></br>
                      <%= check_empty_detail(which_detail_type(@trip_activity,"city")) %>, <%= check_empty_detail(which_detail_type(@trip_activity,"state")) %>
                      <%= check_empty_detail(which_detail_type(@trip_activity,"zip")) %>
                    </address>  
                  </dd>
                  <dt>Description: </dt>
                  <dd>
                    <%= check_empty_detail(which_detail_type(@trip_activity,"description")) %>
                  </dd>
                  <dt>Category: </dt>
                  <dd>
                    <%= check_empty_detail(which_detail_type(@trip_activity,"category")) %>
                  </dd>
                  <dt>Open Hours:</dt>
                  <dd>
                    <%= check_empty_detail(which_detail_type(@trip_activity,"open_hours")) %>
                  </dd>
                  <dt>Phone:</dt>
                  <dd>
                    <%= check_empty_detail(which_detail_type(@trip_activity,"phone")) %>
                  </dd>
                  <dt>Website:</dt>
                  <dd>
                    <%= link_to  check_empty_detail(which_detail_type(@trip_activity,"website")).to_s, check_empty_detail(which_detail_type(@trip_activity,"website")).to_s, :target => "_blank", :class => "caption_subtitle" %>
                  </dd>
                  </dl>
                  <div class="foursquare_attribution">Powered by <div id ="accordion_foursquare_logo"></div></div>
                </div>
                <!-- End more-info-buffer-content -->
              </div>
            </div>
            <!-- End Tab Pane 2 -->
            
            <!-- Begin Tab Pane 3 -->
            <div class="rc_activity_tabs_pane tab-pane" id="<%= "rc_activity_tabs_3_#{@trip_activity.id}" %>">
              <% activity_reviews = comments_collection(@trip_activity) %>
              <% if activity_reviews.blank? %>
                <p>No Reviews are available at this time</p>
              <% else %> 
                <% activity_reviews.each do |review_item| %>
                  <p>
                    <%= review_item.log %> - <a href = "<%= review_item.url %>" target = "_blank"><%= review_item.name %></a>
                  </p>
                <% end %>
                <div class="foursquare_attribution">Powered by <div id ="accordion_foursquare_logo"></div></div>
              <% end %>

            </div>
            <!-- End Tab Pane 3 -->

          </div>
          <!-- End Tab Content -->
        </div>
        <!-- End rc_tabs_con -->      
      </div>
      <!-- End rightcaption -->   
 
        <div class= "front">
          <div class="main_pic_wrap" id="bloop">
            <div data-picture data-alt="<%=alt_name_card_image(@trip_activity)%>" data-class="relative_image">
              <!-- upload_or_foursquare_image_url_picker (object, self_image_size=:thumb, foursquare_image_width=250, foursquare_image_index=0) -->
              <% use_this_url_thumb, which_url_msg_thumb = upload_or_foursquare_image_url_picker(@trip_activity,:thumb, 300, 0) %>
              <% use_this_url, which_url_msg = upload_or_foursquare_image_url_picker(@trip_activity,:card, 767, 0) %>
        
                <div data-src=<%= use_this_url_thumb %> > </div>
                <div data-src=<%= use_this_url_thumb %> data-media="(min-width: 480px)"></div>
                <div data-src=<%= use_this_url %> data-media="(min-width: 767px)"></div>
                <!--[if (lt IE 9) & (!IEMobile)]>
                <div data-src="<%=use_this_url_thumb %>"></div>
                <![endif]-->
                <!-- Fallback content for non-JS browsers. Same img src as the initial, unqualified source element. -->
                <noscript>
                  <img src=<%= use_this_url_thumb %> alt="Image of Activity">
                </noscript>                
            </div>
          </div>   
        </div>

  </div>
  <!-- End centerimage -->

</div>
<!-- End activitycontainer -->  

app/views/trip_activities/partials/_trip_activities_admin_partial.html.erb
<table class ="table table-bordered">
  <tr>
    <th>Activity Day</th>
    <th>Activity Sequence Number</th>
    <th>Activity Time Type</th>
    <th>Activity Type</th>
    <th>Activity Name</th>
    <th>Admin?</th>
  </tr>

<% @trip_activities.each_with_index do |trip_activity, index| %>
  <% unless index == 0 %>
    <%= @trip_activities[index-2].activity_time_type %>
  <%end %>
  <tr>
    <td><%= trip_activity.activity_day %></td>
    <td><%= trip_activity.activity_sequence_number %>
        <% unless @trip_activities.first.activity_sequence_number == trip_activity.activity_sequence_number %> 
          <%= link_to "up", { :action => 'move', :method => 'move_higher', :trip_activity_id => trip_activity.id, :time_type => (trip_activity.activity_time_type), :remote => true } %> 
          <%= link_to "top", { :action =>'move', :method => 'move_to_top', :trip_activity_id => trip_activity.id, :time_type => trip_activity.activity_time_type, :remote => true }  %> 
        <% end %> 

        <% unless @trip_activities.last.activity_sequence_number == trip_activity.activity_sequence_number %>
          <% unless trip_activity.activity_sequence_number == (@trip_activities.first.activity_sequence_number || @trip_activities.last.activity_sequence_number) %> | 
          <% end %> 
          <%= link_to "down", { :action => 'move', :method => 'move_lower', :trip_activity_id => trip_activity.id, :time_type => trip_activity.activity_time_type, :remote => true } %> 
          <%= link_to "bottom", { :action => 'move', :method => 'move_to_bottom', :trip_activity_id => trip_activity.id, :time_type => trip_activity.activity_time_type, :remote => true } %> 
        <% end %>
    </td>

    <td><%= trip_activity.activity_time_type %></td>
    <td><%= (which_detail_type(trip_activity,"name")) %></td>
    <td><%= trip_activity.activity_type %></td>
    
    <% if admin? %>
      <td><%= link_to 'Show', trip_trip_activity_path(@trip, trip_activity) %></td>
      <td><%= link_to 'Edit', edit_trip_trip_activity_path(@trip, trip_activity) %></td>
      <td><%= link_to 'Destroy', [@trip, trip_activity], method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    
  </tr>
<% end %>
</table>

app/views/trip_activities/partials/_trip_activity_creation_successful.html.erb
Activity Successfully Added!

app/views/trip_activities/partials/_trip_activity_destroy_successful.html.erb
<% if ((@trip_activity and @trip_activity.errors.any?) or (@activity and @activity.errors.any?)) %>
  <div id="error_explanation">
   <h2><%#= pluralize(@trip_activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

   <ul>
     <% if @trip_activity %>
       <% @trip_activity.errors.messages.each do |attr, msg| %>
         <li><%= msg.first %></li>
       <% end %>
     <% end %>
     <% if @activity %>
       <% @activity.errors.messages.each do |attr, msg| %>
         <li><%= msg.first %></li>
       <% end %>
     <% end %>
   </ul>
  </div>
<% else %>
  <%= @success_msg %>
<% end %>

app/views/trip_activities/partials/_trip_activity_update_successful.html.erb
Activity Successfully Updated!