config/routes.rb
Travel::Application.routes.draw do
  
  get "author_info/about_edit"
  put "author_info/about_update"

  devise_for :author_infos, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "devise_registrations_callbacks"}

  get "login" => "sessions#new"
  get "logout" => "sessions#del"
  match "sessions" => "sessions#create", :via => :post

  get "venues/pick"
  get "venues/get_venue_info"
  get "venues/get_venue_photos"
  get "venues/get_venue_details"

  get "locations/pick"

  
  %w[about privacy tos why].each do |page|
    get page, :controller => "info", :action => page
  end
  
  resources :author_info do
    member do
      get 'author_page'
    end
  end  
  resources :trip_activities
  resources :trips do
    member do
      get 'showpartial'
      get 'daymapinfo'
      get 'publish_edit'
      get 'publish_confirm'
      get 'publish_add_day'
      get 'publish_delete_day'
      get 'publish_trip_partial_format'
      get 'publish_up_vote'
      put 'publish_update'
      put 'update_individual'
      put 'publish_confirm_update'
      post 'publish_chalo_feedback'
    end
    collection do
      get 'trips_admin'
      get 'publish_new'
      post 'publish_create'
      post 'edit_individual'
    end
    resources :trip_activities do
      member do
        get 'mapinfo'
        get 'carddeck'
        get 'showpartial'
        get 'show_activity_photos'
        get 'publish_trip_activity_edit'
        put 'publish_trip_activity_update'
        post 'add_new_photo'
        delete 'publish_trip_activity_destroy'
      end
      collection do
        get 'move'
        get 'publish_trip_activity_new'
        post 'publish_trip_activity_create'
      end
    end
  end # I nested trip_activities into trips so that we can have routes with /trip/:trip_id/trip_activities/:id hkl
  

  root :to => 'trips#index', :featured => '1'
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end
  
  constraints resque_constraint do
    mount Resque::Server, :at => "/resque"
  end

  
  match "/:username" => "author_info#author_page", via: "get"
  
  unless Rails.application.config.consider_all_requests_local
     match '*not_found', :to => 'errors#error_404'
  end
end

app/views/trips/partials/publish/_completion_status_widget.html.erb
<ul class="nav nav-tabs" id="publish_create_tabs">
  <!-- First Tab -->
  <li class="<%= case controller.action_name 
  					when "publish_new"
  					  'active'
  					when "publish_edit"
  					  ''
  					when "publish_confirm"
  					  'disabled'
  					else
  					  'disabled'
  					end 
  			%>">
  	<%= case controller.action_name 
		  when "publish_new"
		    "<a><i class='icon-check-empty'></i> 1. Trip Info</a>".html_safe
		  when "publish_edit"
		    "<a href='#trip_details' data-toggle='tab'><i class='icon-check' style='color:#3cc574;'></i> 1. Trip Info</a>".html_safe
		  when "publish_confirm"
		   	"<a><i class='icon-check' style='color:#3cc574;'></i> 1. Trip Info</a>".html_safe
		  else
		    "<a>1. Trip Info</a>".html_safe
		  end
	%> 	
  </li>
  <!-- Second Tab -->
  <li class="<%= case controller.action_name 
  					when "publish_new"
  					  'disabled'
  					when "publish_edit"
  					  'active'
  					when "publish_confirm"
  					  ''
  					else
  					  'disabled'
  					end 
  			%>">
  	<%= case controller.action_name 
		  when "publish_new"
		    "<a><i class='icon-check-empty'></i> 2. Add Activities</a>".html_safe
		  when "publish_edit"
		    "<a href='#add_activities' data-toggle='tab'><i class='icon-check-empty'></i> 2. Add Activities</a>".html_safe
		  when "publish_confirm"
		   	link_to("<i class='icon-check' style='color:#3cc574;'></i> 2. Add Activities".html_safe, publish_edit_trip_url(@trip))
		  else
		    "<a>2. Add Activities</a>".html_safe
		  end
	%> 	
  </li>
   <!-- Third Tab -->
  <li class="<%= case controller.action_name 
  					when "publish_new"
  					  'disabled'
  					when "publish_edit"
  					  ''
  					when "publish_confirm"
  					  'active'
  					else
  					  'disabled'
  					end 
  			%>">
  	<%= case controller.action_name 
		  when "publish_new"
		    "<a><i class='icon-check-empty'></i> 3. Review</a>".html_safe
		  when "publish_edit"
		  	if @trip.share_status == 0
		  	  link_to("<i class='icon-check-empty'></i> 3. Review".html_safe,publish_confirm_trip_url(@trip))
		    elsif @trip.share_status == 1
		      link_to("<i class='icon-check-empty'></i> 3. Review".html_safe,publish_confirm_trip_url(@trip))
		    end
		  when "publish_confirm"
		  	if @trip.share_status == 0
		      "<a><i class='icon-check-empty'></i> 3. Review</a>".html_safe
		    elsif @trip.share_status == 1
		      "<a><i class='icon-check-empty'></i> 3. Review</a>".html_safe	
		    end
		  else
		    "<a>3. Publish Trip</a>".html_safe
		  end
	%> 	
  </li> 
</ul>