config/routes.rb
Travel::Application.routes.draw do
  
  get "author_info/about_edit"
  put "author_info/about_update"

  devise_for :author_infos, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "devise_registrations_callbacks"}

  get "login" => "sessions#new"
  get "logout" => "sessions#del"
  match "sessions" => "sessions#create", :via => :post

  get "venues/pick"
  get "venues/get_venue_info"
  get "venues/get_venue_photos"
  get "venues/get_venue_details"

  get "locations/pick"

  
  %w[about privacy tos why].each do |page|
    get page, :controller => "info", :action => page
  end
  
  resources :author_info do
    member do
      get 'author_page'
    end
  end  
  resources :trip_activities
  resources :trips do
    member do
      get 'showpartial'
      get 'daymapinfo'
      get 'publish_edit'
      get 'publish_confirm'
      get 'publish_add_day'
      get 'publish_delete_day'
      get 'publish_trip_partial_format'
      get 'publish_up_vote'
      put 'publish_update'
      put 'update_individual'
      put 'publish_confirm_update'
      post 'publish_chalo_feedback'
    end
    collection do
      get 'trips_admin'
      get 'publish_new'
      post 'publish_create'
      post 'edit_individual'
    end
    resources :trip_activities do
      member do
        get 'mapinfo'
        get 'carddeck'
        get 'showpartial'
        get 'show_activity_photos'
        get 'publish_trip_activity_edit'
        put 'publish_trip_activity_update'
        post 'add_new_photo'
        delete 'publish_trip_activity_destroy'
      end
      collection do
        get 'move'
        get 'publish_trip_activity_new'
        post 'publish_trip_activity_create'
      end
    end
  end # I nested trip_activities into trips so that we can have routes with /trip/:trip_id/trip_activities/:id hkl
  

  root :to => 'trips#index', :featured => '1'
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end
  
  constraints resque_constraint do
    mount Resque::Server, :at => "/resque"
  end

  
  match "/:username" => "author_info#author_page", via: "get"
  
  unless Rails.application.config.consider_all_requests_local
     match '*not_found', :to => 'errors#error_404'
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :country, :latitude, :location_id, :longitude, :place, :state
  has_many :trips, :primary_key => :location_id
  validates_uniqueness_of :location_id, :message => "location already present"

  def location_label
    temp_label = ""
    temp_label = self.city.blank? ? temp_label : temp_label + "#{self.city}"
    temp_label = self.state.blank? ? temp_label : temp_label + ", #{self.state}"
    temp_label = self.country.blank? ? temp_label : temp_label + ", #{self.country}"
  end
end

app/views/trips/partials/trips_admin/_multiple_fields.html.erb
<% if params[:field].blank? || params[:field] == "trip_name" %>
	<div class="control-group">
	    <%= f.label :trip_name, :class => "control-label" %>
	    <div class="controls">
	    	<%= f.text_field :trip_name %>
	    </div>
	</div>
<% end %>

<% if params[:field].blank? || params[:field] == "rank_score" %>
  <div class="control-group">
    <%= f.label :rank_score , :class => "control-label" %>
    <div class="controls">
  	  <%= f.text_field :rank_score %>
  	</div>
  </div>
<% end %>

<% if params[:field].blank? || params[:field] == "featured_trip_flag" %>
  <div class="control-group">
    <%= f.label :featured_trip_flag, 'Featured Trip', :class => "control-label" %>: 
    <div class="controls">
      <%= f.check_box :featured_trip_flag %>
    </div>
  </div>
<% end %>

<% if params[:field].blank? || params[:field] == "trip_summary" %>
  <div class="control-group">
    <%= f.label :trip_summary, :class => "control-label" %>
    <div class="controls">
  	<%= f.text_area :trip_summary, :rows => "4" %>
  	</div>
  </div>
<% end %>

<% if params[:field].blank? || params[:field] == "traveler_type_id" %>
  <div class="control-group">
    <%= f.label :traveler_type_id, 'For', :class => "control-label" %>: 
    <div class ="controls">
      <%= f.collection_select :traveler_type_id, TravelerType.all, :traveler_type_id, :traveler_type_name %>
    </div>
  </div>
<% end %>

<% if params[:field].blank? || params[:field] == "author_id" %>
  <div class="control-group">
    <%= f.label :author_id, :class => "control-label" %>
    <div class ="controls">
    <%= f.text_field :author_id %>
    </div>
  </div>
<% end %>

<% if params[:field].blank? || params[:field] == "duration" %>
  <div class="control-group">
    <%= f.label :duration, :class => "control-label" %>
    <div class ="controls">
    <%= f.text_field :duration %>
	</div>
  </div>
<% end %>

app/views/trips/partials/trips_admin/_trips_admin_partial.html.erb
<%= form_tag edit_individual_trips_path do %>
  <table class ="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th>Trip Rank Score</th>
      <th>Featured Trip?</th>
      <th>Trip Name</th>
      <th>Trip Summary</th>
      <th>Traveller Type</th>
      <th>Author</th>
      <th>Location</th>
      <th>Duration</th>
      <th>Admin</th>
    </tr>
  </thead>

  <tbody>
  <%  for trip in @trips %>
    <tr>
      <td><%= check_box_tag "trip_ids[]", trip.id %></td>
      <td><%= trip.rank_score %></td>
      <td><%= trip.featured_trip_flag %></td>
      <td><%= trip.trip_name %></td>
      <td><%= trip.trip_summary %></td>
      <td><%= trip.traveler_type[:traveler_type_name] %></td>
      <td><%= trip.author_info.author_name %></td>
      <td><%= trip.location[:place] %></td>
      <td><%= trip.duration %></td>
      
      <% if admin? %>
        <td><%= link_to 'Show', trip_path(trip) %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      
    </tr>
  <% end %>
  </tbody >
  </table>
  
  <p><%= select_tag :field, options_for_select([["All Fields", ""], ["Rank", "rank_score"], ["Featured", "featured_trip_flag"], ["Name", "trip_name"], ["Summary", "trip_summary"], ["Traveler Type", "traveler_type_id"], ["Author", "author_id"], ["Location", "location_id"], ["Duration", "duration"]])%></p>

  <p><%= submit_tag "Edit Checked" %></p>
<% end %>