config/routes.rb
Travel::Application.routes.draw do
  
  get "author_info/about_edit"
  put "author_info/about_update"

  devise_for :author_infos, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "devise_registrations_callbacks"}

  get "login" => "sessions#new"
  get "logout" => "sessions#del"
  match "sessions" => "sessions#create", :via => :post

  get "venues/pick"
  get "venues/get_venue_info"
  get "venues/get_venue_photos"
  get "venues/get_venue_details"

  get "locations/pick"

  
  %w[about privacy tos why].each do |page|
    get page, :controller => "info", :action => page
  end
  
  resources :author_info do
    member do
      get 'author_page'
    end
  end  
  resources :trip_activities
  resources :trips do
    member do
      get 'showpartial'
      get 'daymapinfo'
      get 'publish_edit'
      get 'publish_confirm'
      get 'publish_add_day'
      get 'publish_delete_day'
      get 'publish_trip_partial_format'
      get 'publish_up_vote'
      put 'publish_update'
      put 'update_individual'
      put 'publish_confirm_update'
      post 'publish_chalo_feedback'
    end
    collection do
      get 'trips_admin'
      get 'publish_new'
      post 'publish_create'
      post 'edit_individual'
    end
    resources :trip_activities do
      member do
        get 'mapinfo'
        get 'carddeck'
        get 'showpartial'
        get 'show_activity_photos'
        get 'publish_trip_activity_edit'
        put 'publish_trip_activity_update'
        post 'add_new_photo'
        delete 'publish_trip_activity_destroy'
      end
      collection do
        get 'move'
        get 'publish_trip_activity_new'
        post 'publish_trip_activity_create'
      end
    end
  end # I nested trip_activities into trips so that we can have routes with /trip/:trip_id/trip_activities/:id hkl
  

  root :to => 'trips#index', :featured => '1'
  resque_constraint = lambda do |request|
    request.env['warden'].authenticate? and request.env['warden'].user.admin?
  end
  
  constraints resque_constraint do
    mount Resque::Server, :at => "/resque"
  end

  
  match "/:username" => "author_info#author_page", via: "get"
  
  unless Rails.application.config.consider_all_requests_local
     match '*not_found', :to => 'errors#error_404'
  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  layout :resolve_layout
  
  def about
  end

  def privacy
  end

  def tos
  end

  def why
  end

  private
  
  def use_https?
    false # Override in other controllers
  end

  def resolve_layout
    case action_name
    when "why"
      "index_layout"
    else
      "application"
    end
  end

end

app/views/info/_pill_nav.html.erb
<div class="row span12 info_page_pill_nav">
<ul class="nav nav-pills pull-right">
  <%=nav_link("About", about_path)%>
  <%=nav_link("Privacy Policy", privacy_path)%>
  <%=nav_link("Terms of Service", tos_path)%>
</ul>
</div>

app/views/info/about.html.erb
<%= content_for :title do %>
  About Chalo
<% end %>

<%= content_for :description do %>
  <%= "Discover and share experiences to make travel planning easy. Check out trip summaries to " + ((params[:place_text_field] == nil) ? "San Francisco, New York, Paris and Queenstown amongst your other favorite destinations at chalo.io.": (params[:place_text_field]) + " amongst your other favorite destinations at chalo.io.")  %>
<% end %>

<%= render 'pill_nav' %>
<hr>
<div class="row span12">
  <h1>About</h1>

  <p>
  	"Chalo" translates to "Let's Go" in Hindi, a very popular language spoken in India. "Chalo" represents our thirst for exploration, knowledge and shared experiences. </br></br>Planning a new trip is exciting. But it can get time consuming and frustrating. You'll spend hours researching online through an overload of information to piece together the perfect sequence of activities.<br/><br/><b>Chalo helps you search and discover real trips taken by fellow travelers just like you.</b><br/><br/> 
    We would love to hear your thoughts, suggestions and what inspires you - contact us at <%=mail_to "info@chalo.io"%><br/><br/>
  </p>
</div>
<div class="row span12">
  <hr>
  <h1 class="info_align_left">The Caravan</h1>
  <div class="row">  
    <div class="span5">
      <p>
        <span><h3>Sachin Gandhi</h3></span>
      </p>
      <p>It's not the Top 25 things you can do. It's how you do it.</p>
        <%= image_tag('/assets/headshot/sachinga2.jpg', :class=>"team_profile_icon")%>
        Co-founder
  	    <%= link_to image_tag('/assets/logos/izzy_twitter.png', :class=> "team_social_icon"), raw("https://twitter.com/speaksachin"), :target => "_blank"%>
  	   <%= link_to image_tag('/assets/logos/izzy_linkedin.png', :class=> "team_social_icon"), raw("http://www.linkedin.com/in/sachinga"), :target => "_blank"%>
  	   <%= link_to image_tag('/assets/logos/chalo_logo.ico', :class=> "team_social_icon"), '/sachin', :target => "_blank" %>
    </div>
    <div class="span5">
      <p>
        <span><h3>Ivan Gonzalez</h3></span>
      </p>
      <p>Eight countries in the past year.</p>
        <%= image_tag('/assets/headshot/ivan.jpg', :class=>"team_profile_icon")%>
        Co-founder
  	    <%= link_to image_tag('/assets/logos/izzy_twitter.png', :class=> "team_social_icon"), raw("https://twitter.com/ivang"), :target => "_blank"%>
  	   <%= link_to image_tag('/assets/logos/izzy_linkedin.png', :class=> "team_social_icon"), raw("http://www.linkedin.com/in/ivangonzalez"), :target => "_blank"%>
  	   <%= link_to image_tag('/assets/logos/chalo_logo.ico', :class=> "team_social_icon"), '/ivan', :target => "_blank" %>
    </div>
  </div>
  <div class="row">  
    <br/>
    <hr>
    <div class="span5">
      <p>
        <span><h3>Ambrish Verma</h3></span>
      </p>
      <p>Travel is fun, but travel-planning not so much.</p>
        <%= image_tag('/assets/headshot/ambrish.jpg', :class=>"team_profile_icon")%>
        Co-founder
  	    <%= link_to image_tag('/assets/logos/izzy_twitter.png', :class=> "team_social_icon"), raw("https://twitter.com/ambrishverma"), :target => "_blank"%>
  	   <%= link_to image_tag('/assets/logos/izzy_linkedin.png', :class=> "team_social_icon"), raw("http://www.linkedin.com/in/ambrishverma"), :target => "_blank"%>
  	   <%= link_to image_tag('/assets/logos/chalo_logo.ico', :class=> "team_social_icon"), '/ambrish', :target => "_blank" %>
  	</div>
    <div class="span5">
      <p>
        <span><h3>Peter Chang</h3></span>
      </p>
      <p>Discovering local Asian cuisine experiences makes traveling fun.</p>
        <%= image_tag('/assets/headshot/peter.jpg', :class=>"team_profile_icon")%>
        Advisor
        <%= link_to image_tag('/assets/logos/izzy_twitter.png', :class=> "team_social_icon"), raw("https://twitter.com/peter_chang"), :target => "_blank"%>
       <%= link_to image_tag('/assets/logos/izzy_linkedin.png', :class=> "team_social_icon"), raw("http://www.linkedin.com/in/peterschang"), :target => "_blank"%>
       <%= link_to image_tag('/assets/logos/chalo_logo.ico', :class=> "team_social_icon"), '/peter', :target => "_blank" %>
    </div>
	</div>      
  <div class="row">
    <br/>
    <hr>
    <div class="span12">
      <h1>Media</h1><br/>
      <p><blockquote>
        <%= link_to("Five travel startups that pave the way to smarter trip planning", "http://skift.com/2013/05/13/five-travel-startups-pave-the-way-to-smarter-trip-planning/?viewall=1") %>
        - skift.com
      <%= image_tag('/assets/logos/skift-logo.png', :class=>"skift_media_logo")%>
      </blockquote>
    </div>
    <div class="span12"><hr>
      <p><span>Connect with us</span>
        <%= link_to image_tag('/assets/logos/izzy_facebook.png', :class=> "team_social_icon"), raw("https://facebook.com/chalodotio"), :target => "_blank"%>
        <%= link_to image_tag('/assets/logos/izzy_twitter.png', :class=> "team_social_icon"), raw("https://twitter.com/chalodotio"), :target => "_blank"%>
        <%= link_to image_tag('/assets/logos/izzy_instagram.png', :class=> "team_social_icon"), raw("https://instagram.com/chalodotio"), :target => "_blank"%>
      </p>
    </div>
  </div>
</div>

app/views/info/why.html.erb
<%= content_for :title do %>
  Chalo - Why Join? 
<% end %>

<%= content_for :description do %>
  <%= "Discover and share experiences to make travel planning easy. Check out trip summaries to " + ((params[:place_text_field] == nil) ? "San Francisco, New York, Paris and Queenstown amongst your other favorite destinations at chalo.io.": (params[:place_text_field]) + " amongst your other favorite destinations at chalo.io.")  %>
<% end %>

<div class = "why_container">
<section id="why_navigation" class = "showing">
  <div class = "container">
    <ul class="nav nav-pills pull-right nav_pill_parent">
      <!-- <li><a id ="nav_section1" href="#how" class="pill_make_active">How It Works</a></li> -->
      
      <li><a id ="nav_section1" href="#show" class="pill_make_active">Show</a></li>
      <li><a id ="nav_section2" href="#talk" class="pill_make_active">Discuss</a></li>
      <li><a id ="nav_section3" href="#create" class="pill_make_active">Create</a></li>
      <% unless author_info_signed_in? %>
        <%= link_to 'Sign Up Now', new_author_info_registration_url(:protocol => (Rails.env.production?  and CONFIG[:ENABLE_HTTPS] == "yes")  ? "https": "http"), :class => "btn-flat btn-flat-success wn_signup_button" %>
      <% end %>
    </ul>
  </div>
</section>

<section class = "module first_module">
  <a class="anchor" id="show"></a>
  <div class = "container">
    <h2 class = "header">Show Your Trip Summaries to Inspire and Help</h2>

    <ul class = "feature-list two"> 
      <li class = "feature">
        <div class="illustration">
          <div class = "how_search_img"></div>
        </div>
        <h3>Discover</h3>
        <p>It's not just the top 25 things to do. Your trips help other travelers easily decide what they want to do and how. Easily search and filter with Chalo to find the trip summary that works best for you.</p>
      </li>

      <li class = "feature">
        <div class="illustration">
          <div class = "how_show_img"></div>
        </div>
        <h3>Explore and Be Inspired</h3>
        <p>A trip summary presents activities in a meaningful sequence. It provides visual inspiration and also useful information to help you decide what you should go do on your trip.</p>
      </li>
    </ul>
  </div>
</section>

<section class = "module grey_back">
  <a class="anchor" id="talk"></a>
  <div class = "container">
    <h2 class = "header">Discuss and Share Trip Summaries With Others</h2>

    <ul class = "feature-list three long_img"> 
      <div class="illustration ">
        <div class = "how_talk_long_img"></div>
      </div>

      <li class = "feature">
        <h3>Sharing</h3>
        <p>Easily share your trips anywhere with a link or through social channels.</p>
      </li>

      <li class = "feature">
        <h3>Comments</h3>
        <p>Travelers can comment or ask questions about your trip. Provide follow-up tips or receive ideas that you can try next time.</p>
      </li>

      <li class = "feature">
        <h3>Feedback</h3>
        <p>Viewers can provide feedback on how useful a trip summary is or recommend the trip to a friend!</p>
      </li>

    </ul>

  </div>
</section>

<section class = "module">
  <a class="anchor" id="create"></a>
  <div class = "container">
    <h2 class = "header">Trip Summaries Are Easy to Create</h2>
    <ul class = "feature-list two">
      
      <li class = "feature">
        <div class="illustration">
          <div class = "how_create_detailed_img"></div>
        </div>
        <h3>Add Activities</h3>
        <p>Simply use our location database (powered by Foursquare) to tell us where you went each day (in a sequence). Provide a short comment and choose a picture. Voila.</p>
      </li>

      <li class = "feature">
        <div class="illustration">
          <div class = "how_publish_img"></div>
        </div>
        <h3>Title and Publish</h3>
        <p>When you are completely done, add an interesting title and description. Hit publish and share your trip!</p>
      </li>
    </ul>  
  </div>
</section>

<section id="signup" class = "module grey_back">
  <div class = "container">
    
    <% if author_info_signed_in? %>
      <h3>You're signed up! Thank you!</h3>
    <% else %>
      <h2 class = "header">Join Chalo Today</h2>
      <%= link_to 'Sign Up Now', new_author_info_registration_url(:protocol => (Rails.env.production?  and CONFIG[:ENABLE_HTTPS] == "yes")  ? "https": "http"), :class => "btn-flat btn-flat-large btn-flat-success" %>
    <% end %>
    <br><br>
    <p>Just want inspiration? <a href = "http://eepurl.com/zwj59" target = "_blank">Sign Up</a> for our newsletter to get updates.</p>
  </div>
</section>

<section class = "module">
  <a class="anchor" id="how"></a>
  <div class = "container">
    <!-- <h2 class = "header">How It Works</h2> -->
      <ul class = "feature-list three">
        <li class = "feature">
          <div class="illustration">
            <div class = "how_show_img"></div>
          </div>
          <h3>Show</h3>
          <p>Show where you went and what you did in a simple and beautiful trip summary. All in a perfect sequence that anyone can easily follow.</p>
          <a id ="nav_section2" href="#show" class="pill_make_active">Learn More</a>
        </li>

        <li class = "feature">
          <div class="illustration">
            <div class = "how_talk_img"></div>
          </div>
          <h3>Discuss</h3>
          <p>Easily share your trip summary and inspire other travelers. Get feedback and be helpful by engaging with them.</p>
          <a id ="nav_section2" href="#talk" class="pill_make_active">Learn More</a>
        </li>

        <li class = "feature">
          <div class="illustration">
            <div class = "how_create_img"></div>
          </div>
          <h3>Create</h3>
          <p>Creating a trip summary is easy and fun. Just tell us where you went in a sequence.</p>
          <a id ="nav_section2" href="#create" class="pill_make_active">Learn More</a>
        </li>
      </ul>
  </div>
</section>

</div>